version: "3.7"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-fc
    networks:
      - desafio-network

  database:
    container_name: mysql
    image: mysql:latest
    command: --innodb-use-native-aio=0 #?
    restart: always # ?
    tty: true # ?
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
        - MYSQL_DATABASE=desafio
        - MYSQL_ROOT_PASSWORD=1234

    networks:
      - desafio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  node-fc:
    container_name: node-fc
    build: ./node
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - desafio-network
    depends_on:
      database:
        condition: service_healthy
networks:
  desafio-network:
    driver: bridge


 
